name       : libcmis
version    : 0.5.1
release    : 2
source     :
    - https://github.com/tdf/libcmis/archive/v0.5.1.tar.gz : b88851b5e7dfa65b840d403231b38868ba77dae1e7abf2628d7a0dc3cd5a1409
license    :
    - GPL-2.0
    - LGPL-2.1
    - MPL-1.1
component  : programming.library
summary    : C/C++ client library for the CMIS protocol
description: |
    Libcmis aims at providing a C/C++ client library for the CMIS protocol. A cmis-client tool is maintained to help testing and showing libcmis features.
builddeps  :
    - pkgconfig(cppunit)
    - pkgconfig(libcurl)
    - libboost-devel
setup      : |
    %patch -p1 < $pkgfiles/libcmis-fix-google-drive.patch
    %patch -p1 < $pkgfiles/libcmis-google-2FA-implementation.patch
    ./autogen.sh %CONFOPTS% --disable-static \
        --without-man \
        --disable-werror
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/man
    rmdir $installdir/usr/share
