name       : libcmis
version    : 0.5.2
release    : 6
source     :
    - https://github.com/tdf/libcmis/releases/download/v0.5.2/libcmis-0.5.2.tar.xz : d7b18d9602190e10d437f8a964a32e983afd57e2db316a07d87477a79f5000a2
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - MPL-1.1
component  : programming.library
summary    : C/C++ client library for the CMIS protocol
description: |
    Libcmis aims at providing a C/C++ client library for the CMIS protocol. A cmis-client tool is maintained to help testing and showing libcmis features.
builddeps  :
    - pkgconfig(cppunit)
    - pkgconfig(libcurl)
    - libboost-devel
setup      : |
    %configure --disable-static \
        --without-man \
        --disable-werror
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
